[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.2.1"
edition = "2021"
rust-version = "1.76"
authors = ["Alloy Contributors"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/alloy-rs/eips"
repository = "https://github.com/alloy-rs/eips"

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "warn"
redundant-clone = "warn"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
alloy-primitives = { version = "0.7.7", default-features = false }
alloy-rlp = { version = "0.3", default-features = false }

# serde
alloy-serde = { version = "0.2" }
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "alloc",
] }

# kzg
c-kzg = { version = "1.0", default-features = false }
derive_more = "1.0.0"
once_cell = { version = "1.19", default-features = false }
sha2 = { version = "0.10", default-features = false }

# ssz
ethereum_ssz_derive = "0.5"
ethereum_ssz = "0.5"

# arbitrary
arbitrary = "1.3"

# for signed authorization list arbitrary
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }
rand = "0.8"
